class CResultVal;
class CActSimBnd;
class CGridCell;
class CGridLyr;
class CSolver;
class CSsip;
class CPcg;
class CPressPeriod;
class CCHBCell;
class CGDWater;
class CBndCell;
class CPerBndData;
class CBndHandler;
class CGHBCell;
class CGHB;
class CWellCell;
class CWell;
class CDrnCell;
class CDrain;
class CRchgCell;
class CRchg;
extern void PauAndQuit(void);
extern void TrimBlank(CString &str);
